# Generated by Django 4.2 on 2023-05-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='main_category',
        ),
    ]
